<?php
// oh boy isn't this fun
// (used for filtering clean and dirty jokes)
return array(
    'shit',
    'hitler',
    'fuck',
    'fucker',
    'fucking',
    'fucks',
    'fuckers',
    'nigger',
    'niggers',
    'motherfucker',
    'asshole',
    'Assface',
    'asswipe',
    'assholes',
    'prostitute',
    'prostitution',
    'pussy',
    'faggot',
    'faggots',
    'fags',
    'fag',
    'fuckin',
    'nigga',
    'cockhead',
    'cock-head',
    'CockSucker',
    'cock-sucker',
    'cunt',
    'cunts',
    'cock',
    'cocks',
    'shitty',
    'shittiest',
    'shits',
    'ass',
    'bitch',
    "bitch's",
    'bitches',
    'bitchs',
    'cock gobbler',
    'lesbionic',
    'dickhead',
    'dick head',
    'dickheads',
    'dick heads',
    'dickhole',
    'dick hole',
    'slut',
    'Blow Job',
    'Clit',
    'dildo',
    'jackoff',
    'jerk-off',
    'blow jobs',
    'gurgle monster',
    'cum dumpster',
    'Carpet Muncher',
    'fatass',
    'fat-ass',
    'anus',
    'bastard',
    'bastards',
    'butthole',
    'buttwipe',
    'crap',
    'God Damn',
    'God Damned',
    'God Damnit',
    'slut',
    'sluts',
    'Slutty',
    'jizz',
    'testicle',
    'butt-pirate',
    'nutsack',
    'nuttsack',
);

?>